apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: travelx
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: travelx
spec:
  selector:
    app: travelx-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: travelx
spec:
  selector:
    app: travelx-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
