---
- name: Setup TravelX app on EC2 with Docker & Kubernetes
  hosts: travelx
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    # -------------------------------
    # Docker setup
    # -------------------------------
    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    # -------------------------------
    # Kubernetes setup
    # -------------------------------
    - name: Add Kubernetes apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repo
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold kubelet, kubeadm, kubectl at current version
      apt:
        name: "{{ item }}"
        state: present
        mark_hold: yes
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Initialize Kubernetes cluster (only first run)
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configure kubeconfig for ubuntu user
      become_user: ubuntu
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      when: ansible_user == "ubuntu"

    - name: Install Flannel CNI plugin
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

    # -------------------------------
    # App Deployment (choose one)
    # -------------------------------
    - name: Copy docker-compose.yml (optional)
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Start TravelX with Docker Compose
      shell: |
        cd /home/ubuntu && docker-compose up -d
      ignore_errors: yes   # Ignore if you plan to use K8s instead

    - name: Copy K8s manifests
      copy:
        src: ../deploy/k8s/
        dest: /home/ubuntu/k8s/
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Deploy TravelX to Kubernetes
      become_user: ubuntu
      shell: kubectl apply -f /home/ubuntu/k8s/
