name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build backend image
        run: docker build -t ${{ secrets.REGISTRY }}/travelx-backend:latest -f Dockerfile.backend .

      - name: Build frontend image
        run: docker build -t ${{ secrets.REGISTRY }}/travelx-frontend:latest -f Dockerfile.frontend .

      - name: Push backend image
        run: docker push ${{ secrets.REGISTRY }}/travelx-backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.REGISTRY }}/travelx-frontend:latest

      - name: Trivy Scan (backend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.REGISTRY }}/travelx-backend:latest

      - name: Trivy Scan (frontend)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.REGISTRY }}/travelx-frontend:latest

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "TravelX"
          path: "./"
          format: "HTML"
